# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
# This file is *NOT* reloaded automatically when you use 'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# Site settings
# are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

#theme: jekyll-agency
remote_theme: raviriley/agency-jekyll-theme

url    : https://www.crosscures.com/
baseurl: "https://www.crosscures.com" 

title      : CrossCures
email      : kapildevnayar98@gmail.com 
description: "The Future of Healthcare"
author     : Kapil Dev Nayar
logo:     
   path: assets/img/clients/Logo+Text (White Horizontal - Flattened) [Final].svg
   height: 50

locale: "en-US" # See available languages in _data/sitetext.yml

analytics:
  google: <!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-139598782-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-139598782-1');
</script>


collections:
  portfolio:

markdown: kramdown

# Uncomment following line to use Formspree form ID based URL instead of email based URL
# Details: https://help.formspree.io/hc/en-us/articles/360017735154-How-to-prevent-spam
formspree_form_path: "https://formspree.io/f/mdorylqd"

plugins:
  - jekyll-remote-theme
